version: '3'

services:
  db:
      image: postgres
    #   Add if you want to persist data when containers come down
    #   volumes:
    #       - ./data/db:/var/lib/postgresql/data
      environment:
          - POSTGRES_DB=docker_example
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres

  web:
      image: code/web:${IMAGE_VERSION:-latest}
      command: sh conf/web/entrypoint.sh
      volumes:
          - .:/code
      ports:
          - "8000:8000"
      depends_on:
          - db
