version: '3'

services:
  web:
    image: code/web:${IMAGE_VERSION:-latest}
    depends_on:
      - mysql
    command: ['python', 'src/app.py']
    ports:
      - 8800:8800
    volumes:
      - ./conf:/opt/code/conf
      - ./src:/opt/code/src
  mysql:
    image: code/mysql:${IMAGE_VERSION:-latest}
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - default
    volumes:
      - mysql_vol:/var/lib/mysql

volumes:
  web:
  mysql_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
