# Generated by Django 3.2.5 on 2021-07-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=4)),
                ('station_name', models.CharField(max_length=2048)),
                ('station_parent_id', models.CharField(max_length=3)),
                ('station_latitude', models.CharField(max_length=10)),
                ('station_longitude', models.CharField(max_length=10)),
                ('station_line', models.CharField(max_length=64)),
                ('station_borough', models.CharField(max_length=32)),
                ('station_elevated', models.BooleanField()),
                ('northbound_desc', models.CharField(max_length=2048)),
                ('southbound_desc', models.CharField(max_length=2048)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
