# Generated by Django 3.2.9 on 2021-11-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_subway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trains',
            name='train_id',
            field=models.CharField(max_length=12),
        ),
    ]
