# Generated by Django 3.2.5 on 2021-09-16 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_subway', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stations',
            old_name='station_line',
            new_name='station_lines',
        ),
    ]
