# Generated by Django 3.2.9 on 2021-11-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_subway', '0003_traindata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainData',
        ),
    ]
