# Generated by Django 3.2.9 on 2021-11-05 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_subway', '0004_delete_traindata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('record_id', models.CharField(max_length=32)),
                ('train_status', models.CharField(choices=[('1', 'Not Started'), ('2', 'In Transit'), ('3', 'Finished')], max_length=32)),
                ('train_id', models.CharField(max_length=6)),
                ('train_route', models.CharField(max_length=2)),
                ('route_start', models.DateTimeField()),
                ('estimated_time', models.CharField(max_length=64)),
                ('historic_time', models.CharField(max_length=64)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('current_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_station', to='realtime_subway.stations')),
                ('next_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='next_station', to='realtime_subway.stations')),
            ],
        ),
    ]
