# Generated by Django 3.2.9 on 2021-11-24 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_subway', '0004_alter_trains_estimated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trains',
            name='current_stop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_station', to='realtime_subway.stations'),
        ),
    ]
