# Generated by Django 3.2.9 on 2021-11-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_subway', '0005_trains'),
    ]

    operations = [
        migrations.AddField(
            model_name='trains',
            name='train_direction',
            field=models.CharField(default='north', max_length=5),
        ),
    ]
