# Generated by Django 3.2.9 on 2021-11-05 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtime_subway', '0006_trains_train_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trains',
            name='next_stop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_station', to='realtime_subway.stations'),
        ),
    ]
